language: rust
# tarpaulin has only been tested on bionic and trusty other distros may have issues
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev
  snaps:
    - name: node
      confinement: classic
      channel: 15/stable
cache: cargo
rust:
  - nightly

before_script: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
  sudo npm install -g elm-spa@latest
  gunzip elm.gz
  chmod +x elm
  cat scripts/known_hosts >> ~/.ssh/known_hosts
  chmod 400 ./scripts/deployment-key.pem

script:
  - cd backend
  - cargo clean
  - cargo build
  - cargo test
  - cd ..
  - cd frontend
  - ../elm make src/Main.elm --output=../target/elm.js
  - cd ..

after_success: |
  # Create and upload a report for codecov.io
  # Token is not required on Travis-CI, [..] for public repositories.
  cd backend
  cargo tarpaulin --ignore-tests --out Xml --exclude-files ../*
  bash <(curl -s https://codecov.io/bash)

  # Next we also run tests for the library
  cd ../lib
  cargo tarpaulin --ignore-tests --out Xml
  bash <(curl -s https://codecov.io/bash)

  # Now we do the deployment
  cd ..
  chmod +x ./scripts/deploy.sh
  ./scripts/deploy.sh
before_install:
  - openssl aes-256-cbc -K $encrypted_38b64a02c502_key -iv $encrypted_38b64a02c502_iv
    -in scripts/deployment-key.pem.enc -out scripts/deployment-key.pem -d
