language: rust
# tarpaulin has only been tested on bionic and trusty other distros may have issues
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - nightly

before_script: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

script:
  - cd backend
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  # Create and upload a report for codecov.io
  # Token is not required on Travis-CI, [..] for public repositories.
  cd backend
  cargo tarpaulin --ignore-tests --out Xml --exclude-files ../*
  bash <(curl -s https://codecov.io/bash)

  # Next we also run tests for the library
  cd ../lib
  cargo tarpaulin --ignore-tests --out Xml
  bash <(curl -s https://codecov.io/bash)
