[package]
name = "pacosako-tool-server"
version = "0.1.0"
authors = ["Rolf Kreibaum <rolf.kreibaum@posteo.de>"]
edition = "2021"

[dependencies]
kanal = "0.1.0-pre7"
once_cell = "1.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23.0", features = ["full", "tracing"] }
pacosako-rust = { path = "../lib" }
ws = "0.9.1"
uuid = { version = "1.0.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
time = "0.1.43"
simplelog = "0.12.0"
log = "0.4"
async-std = { version = "1.7.0", features = ["attributes"] }
sqlx = { version = "0.5", features = [
    "sqlite",
    "runtime-async-std-rustls",
    "migrate",
] }
async-tungstenite = { version = "0.13", features = ["async-std-runtime"] }
futures = "0.3"
anyhow = "1.0"
thiserror = "1.0"
regex = "1"
lazy_static = "1.4.0"
reqwest = "0.11.10"
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
rocket-cache-response = "0.6.2"
blake3 = "1.3.1"
cached = { version = "0.41.0", default-features = false, features = [
    "proc_macro",
] }

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]
