[package]
name = "pacosako-tool-server"
version = "0.1.0"
authors = ["Rolf Kreibaum <rolf.kreibaum@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
pbkdf2 = "0.3.0"
serde_json = "1.0"
pacosako-rust = { path = "../lib" }
rand = "0.7.3"
ws = "0.9.1"
uuid = "0.8.1"
chrono = { version = "0.4", features = ["serde"] }
time =  "0.1.43"
mio = "0.6.14"
crossbeam-channel = "0.4"
simplelog = "0.8"
log = "0.4"
async-std = { version = "1.6.0", features = [ "attributes" ] }
sqlx = { version = "0.4.0-beta.1", features = ["sqlite"] }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "serve"]
