
[development]
# This secret key is published on github. Don't use it for a production instance.
secret_key = "DZjhqgZ1fDFCnNqxCC+T6K0Y+bKvZGlvg5hc9+oj4yY="

[global.databases]
sqlite_logs = { url = "./data/database.sqlite" }

