[default]
use_min_js = false
# This defines if the cache busting hash is stored after startup or recalculated on every request
cache_js_hashes = false

[debug]
# This secret key is published on github. Don't use it for a production instance.
secret_key = "DZjhqgZ1fDFCnNqxCC+T6K0Y+bKvZGlvg5hc9+oj4yY="
port = 8000
websocket_port = 3010
database_path = "data/database.sqlite"
application_url = "http://localhost:8000"

[staging]
# Staging is running on the prod server as well and is using the dev.pacoplay.com subdomain.
# This is why we need different ports.
port = 8001
websocket_port = 3011
database_path = "../../db/stage.sqlite"
use_min_js = true
cache_js_hashes = true
application_url = "https://dev.pacoplay.com"

[release]
port = 8000
websocket_port = 3012
database_path = "../../db/prod.sqlite"
use_min_js = true
cache_js_hashes = true
application_url = "https://pacoplay.com"
