
[development]
# This secret key is published on github. Don't use it for a production instance.
secret_key = "DZjhqgZ1fDFCnNqxCC+T6K0Y+bKvZGlvg5hc9+oj4yY="
port = 8000
websocket_port = 3010

[staging]
# Staging is running on the prod server as well and is using the dev.pacoplay.com subdomain.
# This is why we need different ports.
port = 8001
websocket_port = 3011

[production]
port = 8000
websocket_port = 3012

[global.databases]
sqlite_logs = { url = "./data/database.sqlite" }

