
[[libpacosako]]
arch = "x86_64"
libc = "glibc"
os = "linux"
git-tree-sha1 = "790d3a72ff181dfc5f9fbba810338cf69b3b899a"

  [[libpacosako.download]]
  url = "https://github.com/kreibaum/pacosako/releases/download/v0.1.0-library-so/libpacosako.tag.gz"
  sha256 = "85ab82096cc99bccfb6ccfb8c0709b84e937f9e4d1035bdb00e28c6bbd76300a"
