[[libpacosako]]
arch = "x86_64"
git-tree-sha1 = "fe4e9f9adecae0e36960db48c68a91a59617af7e"
lazy = true
libc = "glibc"
os = "linux"

    [[libpacosako.download]]
    sha256 = "8006aaed2b3ce97585040206be570ee5bdeed52e4b2c9b4c59649f7a42aceec1"
    url = "https://github.com/kreibaum/pacosako/releases/download/v0.1.1-library-so/libpacosako.tar.gz"

["model.hedwig-0.1"]
git-tree-sha1 = "ba8d2cc5fb054bb2539da3fd230c7118161aac4a"
lazy = true

    [["model.hedwig-0.1".download]]
    sha256 = "357b0783e2382aa2d0628169b363ef3f705e223adf3b2f4064775565020e67c3"
    url = "https://static.kreibaum.dev/hedwig-0.1.tar.gz"

["model.hedwig-0.2"]
git-tree-sha1 = "136b324998f4abc07bbe33c121c418eeb4213c5b"
lazy = true

    [["model.hedwig-0.2".download]]
    sha256 = "ab2b31b32b736eafd37a3199f9a4ccbfe8abb3bea8be1181f5fccf367a176f09"
    url = "https://static.kreibaum.dev/hedwig-0.2.tar.gz"

["model.ludwig-1.0"]
git-tree-sha1 = "2fb78bae27c750adbd417de6e856db406a01f630"
lazy = true

    [["model.ludwig-1.0".download]]
    sha256 = "2e2e47146da21632ea7ac8eb6992a92e0d8569adc788dca0b1a78ce6582900c9"
    url = "https://static.kreibaum.dev/ludwig-1.0.tar.gz"

["model.ludwig-1.0-human"]
git-tree-sha1 = "3a1e0ed2a66aa20929993fa23fa63ff98e8e0a65"
lazy = true

    [["model.ludwig-1.0-human".download]]
    sha256 = "b21ac9bbd5f72318aa573b59ecfc9f2830f8f8bec8bb8953416f36b1ee1be7ed"
    url = "https://static.kreibaum.dev/ludwig-1.0-human.tar.gz"
