name = "JtacPacoSako"
uuid = "e3b14c4e-8e3e-41df-bb37-0c4a418d7b7d"
authors = ["Rolf Kreibaum and Thomas Staudt <tscode@posteo.net>"]
version = "0.1.0"

[deps]
Jtac = "ff1b8621-ed28-5f2d-82b1-1136b8fa4e8d"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LazyJSON = "fc18253b-5e1b-504c-a4a2-9ece4944c004"

[compat]
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
