name: deploy-test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup SSH Keys and known_hosts
        run: |
          ssh-agent -s
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          cat scripts/known_hosts >> ~/.ssh/known_hosts
          
      - name: Create file for upload
        run: echo "Lorem Ipsum" > test-data

      - name: Upload to pacoplacy.com host
        run: |
          scp test-data pacosako@pacoplay.com:~
