# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          backend/target
          lib/target
          ~/.cargo
        key: unittest
        
    - name: Install SQLX-tooling
      run: cargo install sqlx-cli --no-default-features --features sqlite
        
    - name: Run library tests
      run: | 
        pwd
        cd lib
        cargo test
        cd ..
        
    - name: Run backend tests
      run: | 
        pwd
        cd backend
        mkdir -p data
        sqlx database create
        sqlx migrate run
        cargo test
        cd ..

  build:
    name: Build artifact
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          backend/target
          ~/.cargo
        key: build
        
    - uses: actions/setup-node@v2
    
    - name: Install Elm
      run: sudo npm install -g elm elm-spa@latest typescript uglify-js --unsafe-perm=true --allow-root
    
    - name: Compile Frontend
      run: |
        mkdir -p target
        cp frontend/static/* target/
        cd frontend
        elm-spa build
        elm make src/Main.elm --output=../target/elm.js
        cd ..
        # Typescript
        tsc
            
    - name: Install SQLX-tooling
      run: cargo install sqlx-cli --no-default-features --features sqlite
    
    - name: Compile Server in release mode
      run: |
        cd backend
        mkdir -p data
        sqlx database create
        sqlx migrate run
        cargo build --release
        cd ..
